Repository prgrms-fe-devcourse/NFE1_2_Youngstar, pull requests merged in 2024-10, with the labels that each got.

#36 [Feat] 로그인과 회원가입 기능 구현하기 -2
  package-lock.json
  src/assets/Group.png
  src/assets/Group1.png
  src/assets/bigLogo.png
  src/assets/pageLogo.png
  src/assets/welcomeLogo.svg
  src/components/FormLayout.tsx
  src/components/Input.tsx
  src/components/PasswordToggle.tsx
  src/hooks/useAuth.ts
  src/hooks/useFetchUsers.ts
  src/pages/APITest.tsx
  src/pages/JoinPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/routes.tsx
  src/styles/css/Setting.css
  src/styles/css/join.css
  src/styles/css/login.css
  src/styles/scss/join.scss
  src/styles/scss/login.scss
  src/types/AuthTypes.ts
  src/types/FormTypes.ts
  src/types/InputTypes.ts
  src/types/PasswordTypes.ts
Labels: 🍀feature, ✅테스트

#45 [feat] 알림페이지에 데이터를 출력한다
  src/hooks/useFetchNotification.ts
  src/pages/NotificationPage.tsx
  src/styles/css/NotificationPage.css
  src/styles/css/join.css
  src/styles/scss/NotificationPage.scss
Labels: 🍀feature

#51 [Feat] 토큰 저장 및 인증 구현
  .gitignore
  index.html
  package-lock.json
  package.json
  public/index.html
  src/components/Navbar.tsx
  src/components/Post.tsx
  src/hooks/useAuth.ts
  src/hooks/useFetchNotification.ts
  src/hooks/useFetchPost.ts
  src/hooks/useFetchUser.ts
  src/hooks/useFetchUserPost.ts
  src/hooks/useFetchUsers.ts
  src/pages/HotPost.tsx
  src/pages/JoinPage.tsx
  src/pages/LoginPage.tsx
  src/pages/MainPage.tsx
  src/pages/MapPage.tsx
  src/pages/MyPage.tsx
  src/pages/NotificationPage.tsx
  src/routes.tsx
  src/styles/css/Map.css
  src/styles/css/Mypage.css
  src/styles/scss/Map.scss
  src/styles/scss/Mypage.scss
  tsconfig.json
Labels: 🍀feature, ❓question

#54 Feat/#52
  src/components/Header.tsx
  src/hooks/useFetchUsers.ts
  src/styles/css/DetailPage.css
  src/styles/css/Header.css
  src/styles/css/Post.css
  src/styles/scss/Header.scss
  src/types/Search.ts
  src/types/Userpage.ts
Labels: 🍀feature

#55 Feat/#50
  package-lock.json
  package.json
  src/assets/Liked.svg
  src/assets/like_btn_on.svg
  src/assets/notLiked.svg
  src/components/Header.tsx
  src/components/Posts.tsx
  src/hooks/useFetchUsers.ts
  src/pages/DetailPage.tsx
  src/pages/HotPost.tsx
  src/pages/MyPage.tsx
  src/styles/css/DetailPage.css
  src/styles/css/Post.css
  src/styles/scss/DetailPage.scss
  src/styles/scss/Post.scss
Labels: 🍀feature
