Repository prgrms-fe-devcourse/NFE1_2_Youngstar, pull requests merged in 2024-09, with the labels that each got.

#7 [feat]메인 페이지 작업
  package-lock.json
  package.json
  public/index.html
  src/assets/comments_btn.png
  src/assets/header_logo.svg
  src/assets/like_btn.png
  src/assets/nav1.svg
  src/assets/nav2.svg
  src/assets/nav3.svg
  src/assets/nav4.svg
  src/assets/nav5.svg
  src/assets/nav6.svg
  src/assets/nav7.svg
  src/assets/nav_on1.svg
  src/assets/nav_on2.svg
  src/assets/nav_on3.svg
  src/assets/nav_on5.svg
  src/assets/nav_on6.svg
  src/assets/nav_on7.svg
  src/assets/res_header_alram.svg
  src/assets/res_header_scrap.svg
  src/assets/res_header_search.svg
  src/assets/scrap_btn.png
  src/assets/search_btn.svg
  src/components/Follower.tsx
  src/components/Header.tsx
  src/components/Layout.tsx
  src/components/Navbar.tsx
  src/components/Post.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/routes.tsx
  src/styles/Layout.css
  src/styles/css/DetailPage.css
  src/styles/css/Follower.css
  src/styles/css/Header.css
  src/styles/css/Layout.css
  src/styles/css/MainPage.css
  src/styles/css/Navbar.css
  src/styles/css/Post.css
  src/styles/scss/DetailPage.scss
  src/styles/scss/Follower.scss
  src/styles/scss/Header.scss
  src/styles/scss/Layout.scss
  src/styles/scss/MainPage.scss
  src/styles/scss/Navbar.scss
  src/styles/scss/Post.scss
  src/styles/scss/_mixin.scss
  src/styles/scss/_variables.scss
Labels: 🍀feature

#11 [feat] 마이페이지 구현하기
  src/assets/chun_bong.png
  src/assets/logo_header.png
  src/assets/setting.svg
  src/components/Layout.tsx
  src/pages/MyPage.tsx
  src/styles/css/Layout.css
  src/styles/css/Layout.css.map
  src/styles/css/Mypage.css
  src/styles/css/Mypage.css.map
  src/styles/scss/Layout.scss
  src/styles/scss/Mypage.scss
Labels: ❓question

#12 [feat] 채팅 페이지의 화면 구현
  package-lock.json
  package.json
  src/assets/profile.png
  src/assets/send.png
  src/components/Notice.tsx
  src/components/PageHeader.tsx
  src/pages/ChatPage.tsx
  src/pages/MainPage.tsx
  src/pages/NotificationPage.tsx
  src/routes.tsx
  src/styles/css/ChatPage.css
  src/styles/css/ChatPage.css.map
  src/styles/css/Layout.css
  src/styles/css/Layout.css.map
  src/styles/css/NotificationPage.css
  src/styles/css/NotificationPage.css.map
  src/styles/css/PageHeader.css
  src/styles/css/PageHeader.css.map
  src/styles/scss/ChatPage.scss
  src/styles/scss/Layout.scss
  src/styles/scss/NotificationPage.scss
  src/styles/scss/PageHeader.scss
  tsconfig.app.tsbuildinfo
  tsconfig.node.tsbuildinfo
Labels: 🍀feature

#6 [feat] 알림페이지 화면 구현
  package-lock.json
  src/components/Notice.tsx
  src/pages/NotificationPage.tsx
  src/routes.tsx
  src/styles/Layout.css.map
  src/styles/Layout.scss
  src/styles/NotificationPage.css
  src/styles/NotificationPage.css.map
  src/styles/NotificationPage.scss
  src/styles/PageHeader.css
  src/styles/PageHeader.css.map
  src/styles/PageHeader.scss
Labels: 🍀feature

#19 fix: 충돌한 디자인들을 수정하고, 아이콘을 통일시켰다
  index.html
  package-lock.json
  package.json
  src/assets/nav1.svg
  src/assets/nav2.svg
  src/assets/nav3.svg
  src/assets/nav4.svg
  src/assets/nav5.svg
  src/assets/nav6.svg
  src/assets/nav7.svg
  src/assets/nav_on1.svg
  src/assets/nav_on2.svg
  src/assets/nav_on3.svg
  src/assets/nav_on4.svg
  src/assets/nav_on5.svg
  src/assets/nav_on6.svg
  src/assets/nav_on7.svg
  src/components/Follower.tsx
  src/components/Header.tsx
  src/components/Navbar.tsx
  src/components/Post.tsx
  src/pages/MainPage.tsx
  src/pages/MyPage.tsx
  src/pages/NotificationPage.tsx
  src/routes.tsx
  src/styles/Layout.css.map
  src/styles/Layout.scss
  src/styles/NotificationPage.css
  src/styles/NotificationPage.css.map
  src/styles/NotificationPage.scss
  src/styles/PageHeader.css
  src/styles/PageHeader.css.map
  src/styles/PageHeader.scss
  src/styles/css/ChatPage.css
  src/styles/css/ChatPage.css.map
  src/styles/css/DetailPage.css
  src/styles/css/Header.css
  src/styles/css/Layout.css
  src/styles/css/Layout.css.map
  src/styles/css/MainPage.css
  src/styles/css/Mypage.css
  src/styles/css/Mypage.css.map
  src/styles/css/Navbar.css
  src/styles/css/NotificationPage.css
  src/styles/css/NotificationPage.css.map
  src/styles/css/PageHeader.css.map
  src/styles/css/Post.css
  src/styles/css/login.css
  src/styles/scss/ChatPage.scss
  src/styles/scss/Header.scss
  src/styles/scss/Layout.scss
  src/styles/scss/MainPage.scss
  src/styles/scss/Mypage.scss
  src/styles/scss/Navbar.scss
  src/styles/scss/Post.scss
  src/styles/scss/login.scss
Labels: 🐛버그

#21 [feat] 즐겨찾기 페이지를 구현한다.
  src/assets/postImage1.png
  src/components/Navbar.tsx
  src/pages/ChatPage.tsx
  src/pages/NotificationPage.tsx
  src/pages/StarredPage.tsx
  src/routes.tsx
  src/styles/css/ChatPage.css
  src/styles/css/Layout.css
  src/styles/css/NotificationPage.css
  src/styles/css/PageHeader.css
  src/styles/css/StarredPage.css
  src/styles/scss/ChatPage.scss
  src/styles/scss/Layout.scss
  src/styles/scss/NotificationPage.scss
  src/styles/scss/PageHeader.scss
  src/styles/scss/StarredPage.scss
Labels: 🍀feature

#22 [feat] 글쓰기 페이지를 구현했다
  src/assets/camera.svg
  src/assets/tag.svg
  src/pages/MainPage.tsx
  src/pages/PostFormPage.tsx
  src/routes.tsx
  src/styles/css/ChatPage.css
  src/styles/css/Layout.css
  src/styles/css/MainPage.css
  src/styles/css/PostFormPage.css
  src/styles/scss/ChatPage.scss
  src/styles/scss/Layout.scss
  src/styles/scss/MainPage.scss
  src/styles/scss/PostFormPage.scss
Labels: 🍀feature

#27 feat: 포스트 디테일 페이지 마크업 완료
  src/components/UserLive.tsx
  src/pages/DetailPage.tsx
  src/pages/MainPage.tsx
  src/styles/css/DetailPage.css
  src/styles/css/UserLive.css
  src/styles/scss/DetailPage.scss
  src/styles/scss/UserLive.scss
Labels: 🍀feature

#25 feat:회원가입페이지
  package-lock.json
  package.json
  src/assets/pageLogo.png
  src/pages/JoinPage.tsx
  src/routes.tsx
  src/styles/css/join.css
  src/styles/scss/join.scss
Labels: 🍀feature

#23 [Feat] 마이페이지에서 수정버튼의 modal 구현
  package-lock.json
  package.json
  src/assets/_.png
  src/pages/MyPage.tsx
  src/pages/SettingModal.tsx
  src/styles/css/Mypage.css
  src/styles/css/Setting.css
  src/styles/scss/Mypage.scss
  src/styles/scss/Setting.scss
Labels: 🍀feature, ❓question
